#!/usr/bin/env python3
"""Table 2 under the revised accounting (decisions 2026-09-14): J50 in *unique* human labels, shared ledger, pilot charged
in full, t bound. Merges the main grid (*_v2_shared_full_t.csv) with the supplementary grid (*_grid2_*), interpolates J50
linearly between budgets actually run, flags left-censored cells (ACT >= 50% at the smallest budget) and not-reached cells.

Outputs: 05_results/unified/TABLE2_v2_eps{eps}.csv, TABLE2_v2.tex (rows for main.tex), F7_J50_v2.png.
"""
import glob, os, sys
import numpy as np, pandas as pd

HUB = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
R = os.path.join(HUB, "05_results")
METHODS = [("uniform", "Uniform document sampling (humans)"),
           ("weighted", "Decision-weight importance sampling (humans)"),
           ("strat_pilot", "Stratified by pilot variance (humans)"),
           ("ai_calib", "Active inference, calibrated-judge rule + CV"),
           ("ai_resid", "Active inference, residual-estimated rule + CV"),
           ("ai_robust_0.3", "Active inference, robust mixture + CV"),
           ("weighted_cv", "Decision-weight sampling + judge CV ($\\lambda=1$)"),
           ("weighted_cvl", "Decision-weight sampling + judge CV ($\\lambda$ fitted on pilot)")]
COLS = [("antique", "llm"), ("antique", "rr"), ("antique", "inv"), ("cast19", "llm"), ("cast19", "rr"), ("cast19", "inv"),
        ("dbpedia-entity", "llm"), ("dbpedia-entity", "rr"), ("dl212223", "llm")]
LABEL = {"antique": "ANTIQUE", "cast19": "CAsT 2019", "dbpedia-entity": "DBpedia-Entity", "dl212223": "TREC DL 21--23"}
JL = {"llm": "Qwen3-8B", "rr": "reranker", "inv": "inverted"}


def j50(x, y, target=0.5):
    x = np.asarray(x, float); y = np.asarray(y, float); o = np.argsort(x); x, y = x[o], y[o]
    if y[0] >= target:
        return float(x[0]), "censored"
    for i in range(1, len(x)):
        if y[i] >= target:
            return float(x[i - 1] + (target - y[i - 1]) / (y[i] - y[i - 1]) * (x[i] - x[i - 1])), "ok"
    return float(x[-1]), f"n.r. ({y[-1]:.2f})"


GEN = "v3"   # v3 = population estimand (two-stage bound, 2026-09-14 follow-up); v2 = the superseded remainder-mean runs


def load(gen=None):
    gen = gen or GEN
    if gen == "v3":
        files = glob.glob(f"{R}/sampling_baselines/baselines_*_v3b*_v2_shared_full_t.csv") + glob.glob(f"{R}/active_inference/active_*_v3b*_v2_shared_full_binary_t.csv")
    else:   # the *_v2_* glob already matches the *_grid2_v2_* files; a set removes the former double read
        files = glob.glob(f"{R}/sampling_baselines/baselines_*_v2_shared_full_t.csv") + glob.glob(f"{R}/active_inference/active_*_v2_shared_full_binary_t.csv")
        files = [f for f in files if "_v3b" not in f]
    files = sorted(set(files))
    return pd.concat([pd.read_csv(f) for f in files], ignore_index=True)


def main():
    global GEN
    if len(sys.argv) > 1:
        GEN = sys.argv[1]
    d = load(); out = os.path.join(R, "unified"); os.makedirs(out, exist_ok=True)
    tex = []
    for eps in [0.02, 0.01]:
        g0 = d[d.eps == eps]; rows = []
        for m, _ in METHODS:
            for c, j in COLS:
                g = g0[(g0.collection == c) & (g0.judge == j) & (g0.method == m)]
                if g.empty:
                    continue
                gm = g.groupby("budget_full_eq", as_index=False).agg(docs=("docs_labelled", "mean"), act=("act", "mean"), wrong=("wrong", "max"))
                v, flag = j50(gm.docs, gm.act)
                rows.append(dict(eps=eps, method=m, collection=c, judge=j, J50=v, flag=flag, max_wrong=float(g.wrong.max()),
                                 pilot=float(g.docs_pilot.mean()), budgets=" ".join(str(int(b)) for b in gm.budget_full_eq)))
        t = pd.DataFrame(rows); t.to_csv(os.path.join(out, f"TABLE2_{GEN}_eps{eps}.csv"), index=False)
        if True:
            piv = t.pivot(index="method", columns=["collection", "judge"], values="J50"); flg = t.pivot(index="method", columns=["collection", "judge"], values="flag")
            tex.append(f"% Table 2, revised accounting ({GEN}), eps={eps} (generated by 86_table2_v2.py)")
            for m, label in METHODS:
                cells = []
                for c, j in COLS:
                    if (c, j) not in piv.columns or pd.isna(piv.loc[m, (c, j)]):
                        cells.append("---"); continue
                    v = piv.loc[m, (c, j)]; f = flg.loc[m, (c, j)]
                    cells.append(f"{v:,.0f}" if f == "ok" else (f"$\\le${v:,.0f}" if f == "censored" else f"n.r.\\ ($>${v:,.0f})"))
                tex.append(label + " & " + " & ".join(cells) + "\\\\")
            pil = t.groupby("collection").pilot.mean()
            tex.append("Pilot labels (common to every arm) & " + " & ".join(f"{pil[c]:,.0f}" for c, j in COLS) + "\\\\")
            open(os.path.join(out, f"TABLE2_{GEN}.tex"), "w").write("\n".join(tex) + "\n")
            if eps != 0.02:
                continue
            # figure
            import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt
            fig, ax = plt.subplots(figsize=(9, 3.6))
            keys = [f"{LABEL[c]}\n{JL[j]}" for c, j in COLS]; x = np.arange(len(COLS)); w = 0.1
            for i, (m, label) in enumerate(METHODS):
                vals = [piv.loc[m, (c, j)] if (c, j) in piv.columns else np.nan for c, j in COLS]
                ok = [flg.loc[m, (c, j)] == "ok" if (c, j) in flg.columns else False for c, j in COLS]
                ax.bar(x + (i - 3.5) * w, [v if o else np.nan for v, o in zip(vals, ok)], w, label=label.replace("$\\lambda", "λ").replace("$", ""))
                for xi, v, o in zip(x, vals, ok):
                    if not o and np.isfinite(v):
                        ax.plot(xi + (i - 3.5) * w, v, marker="^", color="k", ms=4)
            ax.set_xticks(x); ax.set_xticklabels(keys, fontsize=7); ax.set_ylabel("$J_{50}$ (unique human labels)")
            ax.set_title("Revised accounting (shared ledger, full pilot), precision at cutoff, ε=0.02; ▲ = not reached at that budget", fontsize=8)
            ax.legend(fontsize=6, ncol=2, frameon=False); fig.tight_layout(); fig.savefig(os.path.join(out, f"F7_J50_{GEN}.png"), dpi=200)
        print(f"eps={eps}"); print(t.pivot(index="method", columns=["collection", "judge"], values="J50").round(0).to_string())
    print("\n".join(tex))


if __name__ == "__main__":
    main()
